allowBuilds:
  '@apollo/protobufjs': true
  '@prisma/engines': true
  prisma: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - unrs-resolver
